// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bkbemociqlnicvjwzbcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJrYmVtb2NpcWxuaWN2and6YmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjIzNTMsImV4cCI6MjA2NTM5ODM1M30.1SveO_b1zmjuunCwprBEmSo63GkHFNfNa7SeS8urfGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);